name: ESLint - CI for Javascript files

on:
  push:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true

      - name: Install Node dependencies
        run: npm install

      - name: Run EsLint
        run: npm run lint
