name: Normalize composer.json

on:
  push:
    paths:
      - "composer.json"

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: normalize composer.json
        run: |
          composer global require ergebnis/composer-normalize
          composer normalize

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Normalize composer.json
